notifications:
  email: false

language: node_js

node_js:
  - 'node'

script:
  - yarn lint
  - yarn coverage
  - yarn benchmark

after_success:
  - yarn add --dev coveralls
  - cat coverage/lcov.info | npx coveralls
