notifications:
  email: false

language: node_js

node_js:
  - '6'
  - 'stable'

script:
  - yarn run lint
  - yarn run coverage

after_success:
  - yarn add --dev coveralls
  - cat coverage/lcov.info | ./node_modules/.bin/coveralls
